# Generated by Django 5.2 on 2025-05-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('region', models.CharField(max_length=50)),
                ('meal_time', models.CharField(max_length=50)),
                ('mood_tags', models.CharField(max_length=255)),
            ],
        ),
    ]
